# Exercise: Modular thinking {.unnumbered}

Modular publishing is a big change. To help you along, we want to introduce you to **modular thinking** with a little exercise. 

A big part in modular publishing is about learning to identify what steps you are taking in your research. This is not something we are used to doing, and this exercise will help you start identifying what steps are involved in your work.

For this exercise, you start off with the first step and final step of a research process. We picked `Research question` as the first step and `Results` as the final one for this exercise. You will be using the results of this exercise in next sections. 

:::{.callout-note}
# Exercise 

Repeatedly add a missing step in between two already existing steps in the diagram. Try to do this for 10 minutes to exhaust your options. 
:::

```{mermaid}
flowchart LR
    A[Research Question] ~~~ B[Result]
```

By adding one step in between, your research process would now look like:
```{mermaid}
flowchart LR
    A[Research Question] ~~~ B[...]
    B ~~~ C[Result]
```

Keep adding in steps between two other steps until your ten minutes are up. Really push yourself to find every potential step involved in your research. This will make it look more and more like this:

```{mermaid}
flowchart LR
    A[Research Question] ~~~ B[...]
    B ~~~ C[...]
    C ~~~ D[...]
    D ~~~ E[Result]
```

:::{.callout-tip}
If you need a drawing tool, we recommend <https://draw.io> for this exercise. Doing it with sticky notes is also helpful! 
:::
